### ISSUE TITLE
Давать в маске поддомены

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/quickmapservices_server#11]
Сейчас в ОСМ адрес такой http://tile.openstreetmap.org/{z}/{x}/{y}.png 
https://qms.nextgis.com/geoservices/448/

А должен быть:
http://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png

**Comment by yellow-sky** [comment]
Форма {a-c} - не конкретная. 
Нужно более точное описание: 
 - что может быть внутри? 
 - какие могут быть знаки препинания и как они должны интепритироваться?
 - {} плохой заместитель. Может [ ]  ?

**Comment by yellow-sky** [comment]
Перед тем, как реализовывать на сервере, эту спеку должны поддерживать наши клиенты:

@drnextgis - NGW
@alisovenko - QGIS Plugin
@karavanjo - ArcGIS Plugin
@4eRTuk - Mobile

**Comment by BishopGIS** [comment]
Мобильное уже поддерживает такой формат записи поддоменов. Скобки фигурные для единообразия и парсер в мобильном уже по ним смотрит. 
Сами значения могут быть перечислением - разделитель **запятая** и диапазоном - разделитель **тире**. Насчет смешивания диапазонов и перечислений - не думал, но наверное стоит заложить, например:
{1,3,7,9-15}
В качестве имени могут быть любые строки которые валидны в URL. Например:
{mega,super,great}

Тут альтернативный вариант предлагался - тупо перечислить все валидные URL полностью - из плюсов, меньше ошибок парсинга. Вот пример от [ArcGIS Online](https://tiles.arcgis.com/tiles/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Background_2/MapServer?cacheKey=9591ee40e4826181): 

> Tile Servers: 

> https://tiles1.arcgis.com/tiles/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Background_2/MapServer
> https://tiles2.arcgis.com/tiles/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Background_2/MapServer
> https://tiles3.arcgis.com/tiles/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Background_2/MapServer
> https://tiles4.arcgis.com/tiles/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Background_2/MapServer

**Comment by yellow-sky** [comment]
Как вариант:
http://josm.openstreetmap.de/wiki/Maps#OpenStreetMapCartoStandard
{switch:...}

**Comment by BishopGIS** [comment]
Хороший вариант

**Comment by simgislab** [comment]
реализован вариант со switch https://qms.nextgis.com/geoservices/2075/
