### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by simgislab** [nextgis/quickmapservices_server#22]

**Comment by simgislab** [comment]
QuickMapServices (QMS) is a public catalog and a service that allows you to add a geodata service (TMS, WMS and others) and have it available in your favorite GIS software in just few clicks.

No more explaining how to add TMS/WMS etc. in your GIS, just enter a name. 

You can use QMS catalog in:
- QGIS with QuickMapServices plugin (![more](http://nextgis.com/blog/quickmapservices/))
- NextGIS Mobile (more)
- NextGIS Web (coming soon!)

![Read](http://docs.nextgis.com/qms_srv_dev/doc/api.html) how you can add your software to the list.

QMS is developed by ![NextGIS](http://nextgis.com).

Important links:

* Demo video (add and use a service in QGIS)
* Report general QMS bugs and request features at ![Github](https://github.com/nextgis/quickmapservices_server/)
* General ![questions](http://nextgis.com/contacts)

**Comment by simgislab** [comment]
QuickMapServices (QMS) это публичный каталог и сервис, который позволяет быстро добавлять источники геоданных (TMS, WMS, GeoJSON) и легко использовать их в любой ГИС. 
QMS разработан ![NextGIS](http://nextgis.com).

Больше никаких долгих объяснений как подключить ваш TMS/WMS сервис в ГИС, просто сообщите его имя и пользователь быстро найдет и добавит его прямо в ГИС. 

QMS уже можно использовать в:
- QGIS с помощью модуля QuickMapServices ([подробнее](http://nextgis.com/blog/quickmapservices/))
- ArcGIS with ArcQMS ([подробнее](http://nextgis.com/blog/quickmapservices/))
- NextGIS Mobile (![подробнее](http://nextgis.com/blog/ngm-2-4/))
- NextGIS Web (скоро!)

![Почитайте](http://docs.nextgis.com/qms_srv_dev/doc/api.html) как можно добавить поддержку QMS в другое программное обеспечение.

Еще:

* Видеодемонстрация (как добавить и использовать сервис в QGIS)
* Оставить сообщения об ошибках QMS и предложения можно на ![Github](https://github.com/nextgis/quickmapservices_server/)
* General ![questions](http://nextgis.com/contacts)

**Comment by lisovenkoNastya** [comment]
https://qms.nextgis.com/about
