### ISSUE TITLE
Change fields shown on the service plate

### ISSUE THREAD

**Issue by simgislab** [nextgis/quickmapservices_server#24]
Remove CRS - it is quite useless
Type should be in CAPS, like on service page (tms->TMS)
Add source and url

**Comment by lisovenkoNastya** [comment]
https://github.com/nextgis/quickmapservices_server/commit/e921fe52a5d907e9dfddb3d7de7ba5d0f0efa7ad
Решили, что source в карточке не нужен.

@yellow-sky , нужна возможность вывода url  в карточку

**Comment by yellow-sky** [comment]
Зачем тут урл? Он страшный и большой. И ничуть не лучше чем CRS

**Comment by simgislab** [comment]
классно было бы увидеть пример как будет выглядеть если добавить не кликабельный урл сереньким

**Comment by yellow-sky** [comment]
https://tiles.arcgis.com/tiles/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Background_2/MapServer/tile/{z}/{x}/{y}

**Comment by lisovenkoNastya** [comment]
Решили, что не нужен урл в списке
