### ISSUE TITLE
warning if license info is missing

### ISSUE THREAD

**Issue by simgislab** [nextgis/quickmapservices_server#35]
If license fields are omitted, before saving a service, issue a warning:

```You haven't specified licensing information for the service. NextGIS doesn't hold responsibility ... Failure to add licensing may result is lower rating, omission from API returns and other limitations. Please consider adding it now.```

Reddish background, exclamation icon.

Two buttons: Edit license, I understand

Add link to Terms of service

@Kinda-me please add text

**Comment by Kinda-me** [comment]
```
You haven't specified license information for this service. By submitting information about this service you confirm that you hold valid rights to distribute this information publicly. NextGIS doesn't take responsibility for user-generated content and possible copyright infringmements. 

Failure to add license information may result in lower rating, omission from API returns and other limitations for this service. Please consider adding it now.
```

**Comment by Kinda-me** [comment]
Вы не указали лицензионную информацию для этого сервиса. Отсутствие лицензионной информации может привести к пониженному рейтингу, исключениям в выдаче через API и другим ограничениям в отношении сервиса. Пожалуйста, добавьте лицензионную информацию сейчас.

Предоставляя информацию о сервисе, вы подтверждаете, что имеете право распространять эту информацию публично. НекстГИС не несет ответственности за пользовательский контент и возможные нарушения интеллектуальных прав. [Пользовательское соглашение](http://nextgis.ru/terms/).

**Comment by lisovenkoNastya** [comment]
сделала пока простой confirm https://github.com/nextgis/quickmapservices_server/commit/8fd807f3d611b923e6760412e7e4de689f05e842

**Comment by simgislab** [comment]
закрываю как решенное, но страницу с раширенным текстом все-таки надо будет сделать в одном из следующих релизов

Спасибо!
