### ISSUE TITLE
Information//Информация

### ISSUE THREAD

**Issue by simgislab** [nextgis/quickmapservices_server#50]
Давайте добавить еще одну категорию в темы писем. 

Сейчас везде "проблемы" одни и нельзя например просто "спасибо, хороший сервис" написать или порекомендовать что-то мирно.

**Comment by yellow-sky** [comment]
Так и назовем, Information?
Мне не очень понятно, что я могу сюда написать Спасибо. 
Information очень близок к Other Problem?

**Comment by simgislab** [comment]
можно 
General Feedback//Общая информация

**Comment by lisovenkoNastya** [comment]
Это тогда всю кнопку на переименовывать. Не "Сообщить о проблеме", а "Связаться с автором"
Но вроде обсуждали, что  Сообщить о проблеме лучше описывает большую часть пользовательских сценариев.

А спасибо можно будет и в комментарии добавить, когда сделаем.

**Comment by lisovenkoNastya** [comment]
Но если действительно нужно, то давайте кнопку тогда переименуем в "Написать автору".
Что думаете?

**Comment by yellow-sky** [comment]
Готово
