### ISSUE TITLE
Добавить поле копирайта

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/quickmapservices_server#6]
При показе слоя часто в правом нижнем углу указываются копирайты на подложку (подложки). Было бы неплохо иметь текст копирайта в АПИ и получать его.

```json
    {
        "id": 98,
        "guid": "fd15d9a6-1ff9-4af6-a60f-6e88e8a309e3",
        "name": "OSM Mapnik",
        "desc": "Моя любимая подложка!",
        "type": "tms",
        "epsg": 3857,
        "copyright_text" : "© OpenStreetMap contributors"
    }
```

**Comment by simgislab** [comment]
copyright_text
copyright_link

видимо так

**Comment by yellow-sky** [comment]
Перенести все поля:
        self.lic_name = None
        self.lic_link = None
        self.copyright_text = None
        self.copyright_link = None
        self.terms_of_use = None

**Comment by yellow-sky** [comment]
DONE - https://qms.nextgis.com/api/v1/geoservices/272/
